write_data(L"<!DOCTYPE html>\n");
write_data(L"<html>\n");
write_data(L"<head>\n");
write_data(L"<meta http-equiv=\"content-type\" content=\"text/html;charset=utf-8\">\n");
write_data(L"	<title>编辑</title>\n");
write_data(L"	<style type=\"text/css\">\n");
write_data(L"	input{width:80px;};\n");
write_data(L"	label{width:80px;}\n");
write_data(L"	</style>\n");
write_data(L"	<script language=\"javascript\" src=\"../xml.js\">   \n");
write_data(L"    </script>\n");
write_data(L"</head>\n");
write_data(L"<body>\n");
write_data(L"		<table id=\"tab\">\n");
write_data(L"			<tr>\n");
write_data(L"				<th>\n");
write_data(L"					<label>序号</label></th>\n");
write_data(L"				<th>\n");
write_data(L"					<label>类型</label></th>\n");
write_data(L"				<th>\n");
write_data(L"					<label>X</label></th>\n");
write_data(L"				</th>\n");
write_data(L"				<th>\n");
write_data(L"					<label>Y</label></th>\n");
write_data(L"				<th>\n");
write_data(L"					<label>预览</label></th>\n");
write_data(L"				</th>					\n");
write_data(L"				<th>\n");
write_data(L"					<label>操作</label>\n");
write_data(L"				</th>\n");
write_data(L"			</tr>\n");
write_data(L"			<tr>\n");
write_data(L"				<th><label>1</label></th>\n");
write_data(L"				<th><select name=\"\" id=\"\"><option value=\"text\">文本</option><option value=\"date\">日期</option><option value=\"time\">时间</option><option value=\"count\">计数器</option><option value=\"picture\">图片</option></select></th>\n");
write_data(L"				<th><input type=\"text\" name=\"x\" value=100></th>\n");
write_data(L"				<th><input type=\"text\" name=\"y\" value=200></th>\n");
write_data(L"				<th><input type=\"text\" name=\"\" id=\"\" value=\"\"></th>\n");
write_data(L"				<th><input type=\"button\" value=\"删除字段\" onClick=\"delRow(this)\"></th>\n");
write_data(L"			</tr>\n");
write_data(L"		</table>\n");
write_data(L"		<fieldset>\n");
write_data(L"			<p>\n");
write_data(L"				<input type=\"button\" value=\"添加字段\" onClick=\"addRow()\">\n");
write_data(L"				<label for=\"\">文件名:</label>\n");
write_data(L"				<input type=\"text\" id='file' value=\"app\">\n");
write_data(L"				<input type=\"submit\" value=\"提交修改\" onClick='doXML(0)'>\n");
write_data(L"				<input type=\"submit\" value=\"删除文件\" onClick='doXML(1)'></p>\n");
write_data(L"		</fieldset>\n");
write_data(L"</body>\n");
write_data(L"</html>\n");