write_data(L"<!doctype html>\n");
write_data(L"<html lang=\"en\">\n");
write_data(L"<head>\n");
write_data(L"	<meta charset=\"UTF-8\" />\n");
write_data(L"	<title>文件管理</title>\n");
write_data(L"	<style type=\"text/css\">\n");
write_data(L"	input{width:80px;};\n");
write_data(L"	label{width:80px;}\n");
write_data(L"	</style>\n");
write_data(L"	<script language=\"javascript\" src=\"../xml.js\">\n");
write_data(L"	\n");
write_data(L"    </script>\n");
write_data(L"</head>\n");
write_data(L"<body>\n");
write_data(L"	<table>\n");
write_data(L"		<input type=\"checkbox\" name=\"file\" value=\"Bike\">I have a bike<br/>\n");
write_data(L"		<input type=\"checkbox\" name=\"file\" value=\"Car\">I have a car<br/>\n");
write_data(L"	</table>\n");
write_data(L"	<fieldset>\n");
write_data(L"		<input type=\"button\" value=\"新建\" onClick=\"window.location.href='xml?action=new'\">\n");
write_data(L"		<input type=\"submit\" value=\"打开\" onClick='doAction(\"open\")'>\n");
write_data(L"		<input type=\"submit\" value=\"删除\" onClick='doAction(\"delete\")'>\n");
write_data(L"		<input type=\"submit\" value=\"拷贝\" onClick='doAction(\"copy\")'>\n");
write_data(L"	</fieldset>\n");
write_data(L"</body>\n");
write_data(L"</html>\n");
write_data(L"</html>\n");